#!/bin/bash
#SBATCH --job-name=to_plink
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100000
#SBATCH --time=0-80:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=ejt89@psu.edu
#SBATCH --chdir=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8
#SBATCH --output=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/log/ejt89-toplink-%j.out
#SBATCH --error=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/log/ejt89-toplink-%j.err

echo "Job started"; date "+%Y-%m-%d.%H:%M:%S"
export CONDA_ENVS_PATH=/home/ejt89/.conda/envs
source /opt/anaconda/etc/profile.d/conda.sh
conda activate /home/ejt89/.conda/envs/ancestry
#source activate /home/ejt89/.conda/envs/ancestry
#conda activate ancestry
conda info --envs
conda list

######################################################
# GTEx: Change VCF to PLINK files: Testing QC steps. #
######################################################

# Stop on any errors and print all commands.
set -uex


#if [ -z "$1" ]; then echo "###   ARGUMENT NEEDED: Provide chromosome   ###"; fi
chr=ALL

	# Arguments fed to PLINK.
	DATADIR=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/data/gtex_v8/transfer.2021-02-12/original_files
	vcf=GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.vcf.gz
	prefix=GTEX-WGS-${chr}

mkdir -p gtex_wgs_v8; cd gtex_wgs_v8
mkdir -p ${chr}; cd ${chr}


# Change VCF to PLINK.
#plink --noweb --vcf ${DATADIR}/${vcf} \
#	--make-bed --out ${prefix}


	# Arguments fed to liftOver.
	oldFile=$DATADIR/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.vcf.gz
	map_chain=$DATADIR/hg38ToHg19.over.chain.gz
	newFile=$DATADIR/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.picardhg38ToHg19.vcf
	REFDIR=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/data/refs/hg19
	new_reference=$REFDIR/hg19.fa

# Change GTEx coordinates from hg38 (GRCh38) to hg19 (GRCh37).
###### This option requires bed files of variants.
######liftOver $oldFile $map_chain $newFile unMapped
# Create dictionary of reference file (chose 1000G hg19 ref).
#picard CreateSequenceDictionary \
#	R=$REFDIR/hg19.fa \
#	O=$REFDIR/hg19.dict
# This option is nicer because it lifts over variants directly on VCF files.
#mkdir -p tmp
#picard -Xmx100g -Djava.io.tmpdir=`pwd`/tmp LiftoverVcf \
#	I=$oldFile \
#	O=$newFile \
#	CHAIN=$map_chain \
#	REJECT=picardhg38ToHg19_rejected_variants.vcf \
#	R=$new_reference

# Change VCF to PLINK.
plink --noweb --vcf ${newFile} \
	--allow-extra-chr \
	--chr 1-22 XY \
	--make-bed --out ${prefix}_hg19





echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"


