#!/bin/bash
#SBATCH --job-name=merge_natam
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=200000
#SBATCH --time=0-80:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=ejt89@psu.edu
#SBATCH --chdir=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8
#SBATCH --output=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/log/ejt89-merge_natam-%j.out
#SBATCH --error=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/log/ejt89-merge_natam-%j.err

echo "Job started"; date "+%Y-%m-%d.%H:%M:%S"
export CONDA_ENVS_PATH=/home/ejt89/.conda/envs
source /opt/anaconda/etc/profile.d/conda.sh
conda activate /home/ejt89/.conda/envs/ancestry
#source activate /home/ejt89/.conda/envs/ancestry
#conda activate ancestry
conda info --envs
conda list

#########################################################################
# Merge NatAm samples from Mao et al. to GTEx and 1000G: 		#
#########################################################################

# Stop on any errors and print all commands.
set -uex

	# Arguments.
	MAO_DIR=/nfs/brubeck.bx.psu.edu/scratch3/arslan/mtnuc_project/analysis/lanc/nam_ref_amartin
	prefix_natam=nam_fwd_cleaned_hg19_ref_sex
	MERGED_DIR=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/merged_gtex1kg/ALL
	prefix_merged=MERGED-WGS-ALL_hg19_biall_nopal_excl
	prefix=NATMERG-WGS-ALL_biall_nopal

#mkdir -p wgs_natam ; cd wgs_natam
#cp -n $MAO_DIR/nam_fwd_cleaned_hg19_ref_sex* .

cd $MERGED_DIR
#cp -n ${MAO_DIR}/${prefix_natam}* ${MERGED_DIR}/.

# Replace the original SNP IDs with a common CHR_POS.
#####bash ../../modify_bim.sh ${prefix_natam}.bim 'Overwrite'

# Create input files for bedtools from the new IDs.
#cat ${prefix_natam}.bim | cut -f1,4 | paste - <(cat ${prefix_natam}.bim | cut -f4) | paste - <(cat ${prefix_natam}.bim | cut -f2) > TESTN
#cat ${prefix_merged}.bim | cut -f1,4 | paste - <(cat ${prefix_merged}.bim | cut -f4) | paste - <(cat ${prefix_merged}.bim | cut -f2) > TESTM

# Intersect to get common SNPs across GTEx and 1000G.
#bedtools intersect -a TESTN -b TESTM > list.common.snps

# Try (and fail) to merge GTEx and 1000G.
# Provides the list (.missnp) of problematic sites. 
#	echo ${prefix_natam} > all_files.txt
#	echo ${prefix_merged} >> all_files.txt
#plink --merge-list all_files.txt --make-bed --out ${prefix}

# Look for the .missnp sites in the GTEx and 1000G files.
####for ID in `cat MERGED-WGS-ALL_biall_nopal-merge.missnp`; do grep $ID GTEX-WGS-ALL_biall_nopal.bim >> TEST.missnp ; grep $ID 1KG-WGS-ALL_biall_nopal.bim >> TEST.missnp ; done

# Exclude the SNPs that seem to be multiallelic.
#	cp NATMERG-WGS-ALL_biall_nopal-merge.missnp exclude.missnp
#plink --bfile ${prefix_merged} --exclude exclude.missnp --make-bed --out ${prefix_merged}_excl
#plink --bfile ${prefix_natam} --exclude exclude.missnp --make-bed --out ${prefix_natam}_excl

# Merge GTEx and 1000G after excluding problematic sites.
#	echo ${prefix_natam}_excl > all_files.txt
#	echo ${prefix_merged}_excl >> all_files.txt
#plink --merge-list all_files.txt --allow-no-sex --make-bed --out ${prefix}

# Filter by maf and missingness.
# Exclude haploid (.hh) sites.
#cat ${prefix}.hh| cut -f3 | sort | uniq > haploid.list
#plink --bfile ${prefix} \
#	--maf 0.01 --geno 0.1 --allow-no-sex \
#	--exclude haploid.list \
#	--make-bed --out ${prefix}_filt

# Extract the common SNPs.
#plink --bfile ${prefix}_filt \
#	--extract list.common.snps --allow-no-sex \
#	--make-bed --out ${prefix}_filt_common

# Prune.
# List of sites to prune.
#plink --bfile ${prefix}_filt_common \
#	--maf 0.01 --geno 0.1 \
#	--indep 50 5 2 --allow-no-sex \
#	--out ${prefix}_filt_common_prune
# Keep that list of pruned sites.
#plink --bfile ${prefix}_filt_common \
#	--extract ${prefix}_filt_common_prune.prune.in \
#	--maf 0.01 --geno 0.1 \
#	--make-bed --out ${prefix}_filt_common_pruned

# Generate IBS values (for pop stratification).
#plink --bfile ${prefix}_filt_common_pruned \
#	--genome \
#	--allow-no-sex --out ${prefix}_genome

# Generate MDS clustering.
#plink --bfile ${prefix}_filt_common_pruned \
#	--read-genome ${prefix}_genome.genome --cluster --K 2 --mds-plot 4 \
#	--allow-no-sex --out ${prefix}_mds

# Create plots.
#Rscript ../../makeplot_mds.R ${prefix}_mds.mds "NATAM_MAO"


# Keep populations for K=3 supervised ADMIXTURE step.
# Excludes most 1000 Genomes populations.
#rm -f GTEX_YRI_CEU_NATAM.keep
#for ID in GTEX CEU YRI ^MAYAN ^NAHUAN ^AYMARAN ^QUECHUAN ; do cat ../../Merged_GTEx-1KG-NATAM_v8.ids | grep $ID| cut -f1  >> GTEX_YRI_CEU_NATAM.keep ; done
#plink --bfile ${prefix}_filt_common_pruned \
#       --keep-fam GTEX_YRI_CEU_NATAM.keep --allow-no-sex \
#       --make-bed --out ${prefix}_filt_common_pruned_keep3


# Keep populations for K=2 supervised ADMIXTURE step.
# Excludes Mao et al. Native Americans, and most 1000 Genomes populations.
#rm -f GTEX_YRI_CEU.keep
#for ID in GTEX CEU YRI; do cat ../../Merged_GTEx-1KG_v8.ids | grep $ID| cut -f1  >> GTEX_YRI_CEU.keep ; done
#plink --bfile ${prefix}_filt_common_pruned \
#       --keep-fam GTEX_YRI_CEU.keep --allow-no-sex \
#       --make-bed --out ${prefix}_filt_common_pruned_keep2

# Keep just the GTEx samples.
# Excludes all 1000G and Mao et al. samples.
cat ../../Merged_GTEx-1KG_v8.ids | grep 'GTEX' | cut -f1 > GTEX_solo.keep
plink --bfile ${prefix}_filt_common_pruned \
       --keep-fam GTEX_solo.keep --allow-no-sex \
       --make-bed --out ${prefix}_filt_common_pruned_soloGTEx



echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"

