#!/bin/bash
#SBATCH --job-name=admix_cv
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=250000
#SBATCH --mail-type=END
#SBATCH --mail-user=ejt89@psu.edu
#SBATCH --chdir=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8
#SBATCH --output=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/log/ejt89-admix-%j.out
#SBATCH --error=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/log/ejt89-admix-%j.err

echo "Job started"; date "+%Y-%m-%d.%H:%M:%S"
export CONDA_ENVS_PATH=/home/ejt89/.conda/envs
source /opt/anaconda/etc/profile.d/conda.sh
conda activate /home/ejt89/.conda/envs/ancestry
#source activate /home/ejt89/.conda/envs/ancestry
#conda activate ancestry
conda info --envs
conda list

#################################################
#  Obtain Global ancestry and make bar plots. 	#
#################################################

# Stop on any errors and print all commands.
set -uex

if [ -z "$1" ]; then echo "###   ARGUMENT NEEDED: K   ###"; fi
K=${1}

	# TOOLS:
	admixture=/home/ejt89/src/admixture_linux-1.3.0/admixture32

	# Arguments fed to ADMIXTURE.
	DATADIR=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8
	prefix=NATMERG-WGS-ALL_biall_nopal_filt_common_pruned
	FILE_BED=${DATADIR}/merged_gtex1kg/ALL/${prefix}.bed
	K=${1}

mkdir -p admix; cd admix

#  Get Cross validation error, using 6 threads.
#$admixture --cv -j6 ${FILE_BED} ${K} | tee cv.${K}.log

# Get cross validation error or GTEx pops without reference populations.
$admixture --cv -j6 ${DATADIR}/merged_gtex1kg/ALL/NATMERG-WGS-ALL_biall_nopal_filt_common_pruned_soloGTEx.bed ${K} | tee cv_norefs.${K}.log


# Unsupervised.
# Run Admixture32 Unsupervised.
#$admixture -j6 ${FILE_BED} $K 

        # Arguments fed to R.
	FILE_Q=${prefix}.${K}.Q
	FILE_FAM=${DATADIR}/merged_gtex1kg/ALL/${prefix}.fam
	IDS=${DATADIR}/Merged_GTEx-1KG-NATAM_v8.ids

# Create global ancestry bar plots.
#Rscript $DATADIR/plt_structure.R \
#	${K} ${FILE_Q} ${FILE_FAM} ${IDS}



# Supervised.
cd $DATADIR ; mkdir -p admix_sup ; cd admix_sup

	K=$1
	prefix_sup=${prefix}_keep${K}
	FILE_BED=${DATADIR}/merged_gtex1kg/ALL/${prefix_sup}.bed
	POP_FILE=${DATADIR}/merged_gtex1kg/ALL/${prefix_sup}.pop

# Create POP (.pop) file.
#bash ${DATADIR}/make_pop.sh ${prefix_sup}

# Run Admixture32 supervised, on 6 threads.
#$admixture -j6 ${FILE_BED} ${K} --supervised ###${POP_FILE} > admix.${K}.log

        # Arguments fed to R.
	#####FILE_Q=NATMERG-WGS-ALL_biall_nopal_filt_common_pruned_keep${K}.${K}.Q
	FILE_Q=${prefix}_keep${K}.${K}.Q
	FILE_FAM=${DATADIR}/merged_gtex1kg/ALL/${prefix_sup}.fam

# Use ID to grep the population code.
rm -f TEMP.ids
for ID in `cat ${FILE_FAM} | cut -f1 -d' '`; do grep $ID ${IDS}  >> TEMP.ids ; done	
	####IDS=TEMP.ids

# Create global ancestry bar plots.
#Rscript $DATADIR/plt_structure.R \
#	${K} ${FILE_Q} ${FILE_FAM} TEMP.ids

#  Get Cross validation error, using 6 threads.
#srun $admixture --cv -j6 ${FILE_BED} 1 | tee cv.${K}.1.log
#srun $admixture --cv -j6 ${FILE_BED} 2 | tee cv.${K}.2.log
#srun $admixture --cv -j6 ${FILE_BED} 3 | tee cv.${K}.3.log
#srun $admixture --cv -j6 ${FILE_BED} 4 | tee cv.${K}.4.log


echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"


