#!/bin/bash
#SBATCH --job-name=plink_splitChr
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=60000
#SBATCH --time=0-80:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=ejt89@psu.edu
#SBATCH --chdir=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/D_localAnc/LocalAnc_v8
#SBATCH --output=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/D_localAnc/LocalAnc_v8/log/ejt89-plink_allChr-%j.out
#SBATCH --error=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/D_localAnc/LocalAnc_v8/log/ejt89-plink_allChr-%j.err

echo "Job started"; date "+%Y-%m-%d.%H:%M:%S"
export CONDA_ENVS_PATH=/home/ejt89/.conda/envs
source /opt/anaconda/etc/profile.d/conda.sh
conda activate /home/ejt89/.conda/envs/ancestry
#source activate /home/ejt89/.conda/envs/ancestry
#conda activate ancestry
conda info --envs
conda list

#########################################################################################################
# Prep for SHAPEIT: Separate a chromosome, split CEU/YRI from GTEx, Plink QC pre-SHAPEIT.  	#
#########################################################################################################

# Stop on any errors and print all commands.
set -uex

if [ -z "$1" ]; then echo "###   ARGUMENT NEEDED: Provide chromosome   ###"; fi
chr=${1}

mkdir -p 'chr'${chr}
	
	input_prefix=MERGED-WGS-ALL_hg19_biall_nopal_excl_filt_common
	prefix=MERGED-WGS-chr{chr}_hg19_biall_nopal_excl_filt_common

# Extract the specified chromosome from the merged file.
plink --bfile ${input_prefix} \
	--chr ${chr}  \
	--allow-no-sex --make-bed --out 'chr'${chr}/${prefix}


cd chr${chr}


# Split All_1kg+EuAm/AfAm merged file into: EuAm/AfAm ; and CEU/YRI.
# Test for missingness per individual, and per marker.
plink --bfile ${prefix} \
	--keep ../SPLIT_GTEx_EuAm-AfAm.ids\
	--mind 0.1 --geno 0.05 \
	--allow-no-sex --make-bed --out WGS-chr${chr}_GTEx
plink --bfile ${prefix} \
        --keep ../SPLIT_1kg_CEU-YRI.ids \
	--mind 0.1 --geno 0.05 \
        --allow-no-sex --make-bed --out WGS-chr${chr}_CEU-YRI

# Check that the number of markers are the same, after testing for missingness in data.
wc -l WGS-chr${chr}_GTEx.bim
wc -l WGS-chr${chr}_CEU-YRI.bim

# PLINK QC (pre-SHAPEIT) for the EuAm/AFAm file.
# Remove missing data and palindromic SNPs (A/T, G/C).
#plink --bfile WGS-chr${chr}_GTEx \
	
# Excludes SNPs in LD.
plink --bfile WGS-chr${chr}_GTEx \
       --indep 50 5 2 \
       --allow-no-sex --make-bed --out WGS-chr${chr}_GTEx_pruned

# Generate IBS values (for pop startification).
plink --bfile WGS-chr${chr}_GTEx_pruned \
       --genome \
       --allow-no-sex --out WGS-chr${chr}_GTEx_pruned_genome

# Generate MDS clustering.
plink --bfile WGS-chr${chr}_GTEx_pruned \
        --read-genome WGS-chr${chr}_GTEx_pruned_genome.genome \
	--cluster --K 2 --mds-plot 4 \
        --allow-no-sex --out WGS-chr${chr}_GTEx_pruned_mds

# Create plots.
Rscript ../makeplot_mds.R WGS-chr${chr}_GTEx_pruned_mds.mds "GTEX"







echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"


