#!/bin/bash
#SBATCH --job-name=to_plink
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=60000
#SBATCH --time=0-80:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=ejt89@psu.edu
#SBATCH --chdir=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8
#SBATCH --output=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/log/ejt89-toplink-%j.out
#SBATCH --error=/nfs/secure/scratch6/nekrut_gtex/ejt89/mito_gtex/bin/B_globalAnc/GlobalAnc_v8/log/ejt89-toplink-%j.err

echo "Job started"; date "+%Y-%m-%d.%H:%M:%S"
export CONDA_ENVS_PATH=/home/ejt89/.conda/envs
source /opt/anaconda/etc/profile.d/conda.sh
conda activate /home/ejt89/.conda/envs/ancestry
#source activate /home/ejt89/.conda/envs/ancestry
#conda activate ancestry
conda info --envs
conda list

#######################################################
# 1000G: Change VCF to PLINK files: Testing QC steps. #
#######################################################

# Stop on any errors and print all commands.
set -uex


if [ -z "$1" ]; then echo "###   ARGUMENT NEEDED: Provide chromosome   ###"; fi
chr=${1}

	# Arguments fed to PLINK.
	#DATADIR=/nfs/brubeck.bx.psu.edu/scratch6/makova_lab/downloads/1000_Genomes_Project/VCF
	#vcf_pref=ALL.chr${chr}.phase3_shapeit2_mvncall_integrated_v
	#vcf_suff=.20130502.genotypes.vcf
	prefix=1KG-WGS-${chr}
	vcf=ALL.chrALL.phase3_shapeit2_mvncall_integrated_v.biallelic.vcf.gz

mkdir -p wgs_1kg; cd wgs_1kg
mkdir -p ${chr}; cd ${chr}


# Change VCF to PLINK.
#plink --noweb --vcf ${DATADIR}/${vcf_pref}*${vcf_suff} \
#	--make-bed --out ${prefix}


# VCF to plink.
plink --make-bed \
	--vcf ALL.chrALL.phase3_shapeit2_mvncall_integrated_v.biallelic.vcf \
	--biallelic-only strict \
	--out ${prefix}_biall


# Remove palindromic snps.
Rscript ../../rm_palindromic.R ${prefix}_biall.bim
plink --make-bed \
	--bfile 1KG-WGS-ALL_biall \
	--biallelic-only strict \
	--extract list.nonpalindromic.snps \
	--out ${prefix}_biall_nopal


# Prune for MDS clustering.
plink --make-bed \
	--bfile 1KG-WGS-ALL_biall_nopal \
	--allow-no-sex \
	--indep 50 5 2 \
	--out ${prefix}_biall_nopal_pruned





echo "Job ended"; date "+%Y-%m-%d.%H:%M:%S"


